/**
 * @class IssuanceRequest
 * @description Represents the payload required to issue a new Verifiable Credential.
 * This class includes only the fields that the client provides to the issuance API.
 * Other fields (like claimID, version, proofs) are generated by the issuer.
 */
class IssuanceRequest {
    /**
     * Creates an instance of IssuanceRequest for an issuance API call.
     * @param {string} credentialSchema - The URL of the credential schema. (Mandatory)
     * @param {string} type - The type of the credential (e.g., "KYCAgeCredential"). (Mandatory)
     * @param {object} credentialSubject - An object containing the claims about the subject. (Mandatory)
     * @param {number} [expiration] - The Unix timestamp of the credential's expiration (Optional).
     */
    constructor(credentialSchema, type, credentialSubject, expiration) {
        if (!credentialSchema || !type || !credentialSubject) {
            throw new Error("credentialSchema, type, and credentialSubject are mandatory for an IssuanceRequest.");
        }

        this.credentialSchema = credentialSchema;
        this.type = type;
        this.credentialSubject = credentialSubject;

        // Only include expiration if it's provided and valid
        if (expiration !== undefined && expiration !== null && !isNaN(expiration)) {
            this.expiration = expiration;
        }
    }

    /**
     * Returns a plain object representation suitable for JSON stringification.
     * This is automatically called by JSON.stringify() if present.
     * @returns {object} The object representation of the issuance request.
     */
    toJSON() {
        const obj = {
            credentialSchema: this.credentialSchema,
            type: this.type,
            credentialSubject: this.credentialSubject
        };
        if (this.expiration !== undefined) {
            obj.expiration = this.expiration;
        }
        return obj;
    }
}

// Export the class so it can be imported in other files.
export { IssuanceRequest };